### PR TITLE
chore: NativeScript 8 touchups

### PR DESCRIPTION
**Pull request by NathanWalker**
* [x] updates all dep's to use latest alpha of NativeScript 8
* [x] confirms successful builds using `build.all`
* [x] confirms successful demos

This can stay on this PR until 8.0 is released with the final version but this prepares everything.

This also intentionally leaves a few areas using the deprecated `Enums.` instead of `CoreTypes.` to confirm that everything works normal with mixed usage.

### CODE REVIEW

**Comment by NathanWalker** [comment]
The eslint change was just switching to @nativescript/eslint-plugin which contains standard rulesets that were there while also adding ability to gain enhancements that will continue to come out with the {N} eslint plugin over time.

**Comment by farfromrefug** [comment]
@NathanWalker thanks a lot! love that `@nativescript` eslint thing. Where is the code for it ?

**Comment by NathanWalker** [comment]
https://github.com/NativeScript/eslint-plugin

**Comment by patrick-nurt** [comment]
@NathanWalker when will this be released? - Tabs are not currently working for me under NS8..

**Comment by NathanWalker** [comment]
@farfromrefug could you help @patrick-nurt out here when you get a chance. Patrick, if you have specific stacktrace if you added the current plugin please share anything additional here.

**Comment by farfromrefug** [comment]
@patrick-nurt what s your code? make sure to change all Tabs, TabContentItem,... with MDTabs, MDTabContentItem ...
I will update the doc

**Comment by farfromrefug** [comment]
@NathanaelA PR merged, doc updated, release coming

**Pull request merged**
