### PR TITLE
fix(tabs) Change image colors on selected tab in IOS and android

### PR DESCRIPTION
**Pull request by jcassidyav**
Included in this pull request:

General:
- Fix tsc-win commands in all packages ( / to // )
- Add build.angular.win  in all packages ( / to // again )
- There is still an issue building and running everything unless a reference to @nativescript-community/ui-material-core package.json.
- 
Demo-ng
- update demo-angular to ns8
- fix tabs xml so it shows up
- Change tabs to use one font based image source

Fixes:

#274 font based images now change color when selected ( resource based images do not )
#282 Color change triggered when Tab selected. 

I noticed two remaining issues.

1. Non font based images don't change color when selected in IOS
2. The line under the tab which shows which tab is selected doesn't honor the highlight-color CSS not sure if that is intended or not.

### CODE REVIEW

**Comment by farfromrefug** [comment]
@jcassidyav that s why i want you to try and force it with `alwaysTemplate`

**Comment by jcassidyav** [comment]
Maybe I am misunderstanding, but I set iosIconRenderingMode="alwaysTemplate" on the MDTabStrip and set the code in getIcon to always set rendermode to 2 and I'm still seeing the icon not change color.

**Comment by farfromrefug** [comment]
@jcassidyav ok then it does not work. Will have to try it. Thanks

**Comment by jcassidyav** [comment]
I don't think the change here has degraded / caused the issue with the images not changing color, would it be possible to just look at this pull request without regard to the images icon issue?

**Comment by farfromrefug** [comment]
@jcassidyav it is now published thanks!

**Pull request merged**
