### PR TITLE
Update READMEs

### PR DESCRIPTION
**Pull request by FestplattenSchnitzel**
It seems all the READMEs are quite outdated. I've updated them.

Things to do:
- [x] Main README: Add links to [Material Design Specs](https://material.io/components?platform=android)
- [x] Package READMEs:
  - [x] Table of contents
  - [x] `Changelog` entries
  - [x] FAQ entries (referring to main README)
  - [ ] ~~API Attributes,  Events, Methods~~ (maybe another MR)
  - [x] Unified `NativeScript` casing
  - [x] h1 titles
  - [x] valid CSS comments
  - [x] update npm shields
- [x] some misc fixes

### CODE REVIEW

**Comment by FestplattenSchnitzel** [comment]
BTW: Can someone please explain to me what's the difference between `Bottom Navigation` and `Bottom Navigation Bar`?

**Comment by farfromrefug** [comment]
@FestplattenSchnitzel bottom navigation bar is a new component to draw a bottom navigation bar in matérial design.
bottom navigation is a simple extract of the component from N. the idea is tonbw able at one to remove it from N. as it uses material libs it has its place here.
in the future things could get refactored. but for now it must remain that way for easy transition

**Comment by farfromrefug** [comment]
@FestplattenSchnitzel already looks really cool !

**Comment by FestplattenSchnitzel** [comment]
@farfromrefug this is now ready from my side.

**Comment by farfromrefug** [comment]
@FestplattenSchnitzel awesome! Thanks a lot!

**Pull request merged**
