### PR TITLE
Upgrades and cleanup for better Angular support

### PR DESCRIPTION
**Pull request by charsleysa**
Adds better support for CardView through directives
Adds AOT support
General cleanup of some code

Some of the work is being merged in from [charsleysa/nativescript-mdc](https://github.com/charsleysa/nativescript-mdc)

### CODE REVIEW

**Comment by farfromrefug** [comment]
@charsleysa thanks. But i don't see the point of your cardview directive. Those properties are declared already and you don't need this. Can you explain?

**Comment by charsleysa** [comment]
@farfromrefug to be honest I can't remember the exact reason there was a directive for card view, I think it had something to do with safety around the lifecycle with angular as there would be cases where the angular component would exist but the underlying nativescript component did not yet exist so programmatic access to the UI element would cause an exception. 

This is the first of a few PRs. I plan on adding the Bottom Navigation component next which has benefits of using the directives in terms of building out the tabs in the HTML template instead of having to do it through code.

My goal is consolidate efforts to bring all the MDC components to nativescript.

**Comment by farfromrefug** [comment]
@charsleysa great! So can you modify that PR and remove the directive for now? Until it's actually proven to be necessary?

**Comment by charsleysa** [comment]
@farfromrefug updated the PR with the directive removed.

**Pull request merged**
